export const ENV = {
  /** For App */
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  OPEN_AI_KEY: process.env.NEXT_PUBLIC_OPEN_AI_KEY,
  FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  AUTHDOMAIN: process.env.NEXT_PUBLIC_AUTHDOMAIN,
  PROJECTID: process.env.NEXT_PUBLIC_PROJECTID,
  STORAGEBUCKET: process.env.NEXT_PUBLIC_STORAGEBUCKET,
  MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  APP_ID: process.env.NEXT_PUBLIC_APP_ID,
  MEASUREMENT_ID: process.env.NEXT_PUBLIC_MEASUREMENT_ID,
  DOC: process.env.NEXT_PUBLIC_DOC,
} as const;
